add allow-unused to grad call in Forces.forward()
Error message:

critical:poptorch::python:RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.

Traceback (most recent call last):
  File "run_simulation_ipu.py", line 26, in <module>
    EthanolSimulation(thermostats, log_files, torch.device("ipu"), 1000, True)
  File "/mnt/masterarbeit/SchNetMDSimulation/src/ethanol_simulation.py", line 43, in __init__
    simulation.start_simulation(steps)
  File "/mnt/masterarbeit/SchNetMDSimulation/src/simulation.py", line 125, in start_simulation
    sim.simulate(n_steps)
  File "/usr/local/lib/python3.8/dist-packages/schnetpack/md/simulator.py", line 117, in simulate
    self.calculator.calculate(self.system)
  File "/mnt/masterarbeit/SchNetMDSimulation/src/SchNetPackCalcIpu.py", line 56, in calculate
    self.results = self.ipu_executor(inputs)
  File "/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py", line 1162, in __call__
    self._compile(in_tensors)
  File "/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py", line 358, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py", line 922, in _compile
    self._executable = self._compileWithDispatch(in_tensors_trace_view)
  File "/usr/local/lib/python3.8/dist-packages/poptorch/_impl.py", line 164, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/poptorch/_poplar_executor.py", line 798, in _compileWithDispatch
    result = self._model(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/schnetpack/model/base.py", line 182, in forward
    inputs = m(inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/schnetpack/atomistic/response.py", line 63, in forward
    grads = grad(
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.